---
title: "Survival"
author: "GS"
date: "24/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = "", warning = F, message = F)
```

# Survival Analysis in R

```{r, packages}
library(tidyverse)
library(survival)
library(ggfortify)
library(survminer)

theme_set(theme_bw())
```


```{r, dataset prostate cancer}
var_names <- c("patient", "treatment", "time", "status", "age", "psa", "size", "gleason")
prostate <- read_delim ("prostate_cancer.txt", delim = " ", col_names = var_names)

glimpse(prostate)
```
### KM sin grupos

```{r, km sin grupo}
Surv(prostate$time, prostate$status)

km1 <- survfit(Surv(prostate$time, prostate$status) ~ 1) # el 1 es xq es sin grupos

plot(km1, mark.time = T)
```

### KM con 2 grupos
```{r, km con grupos}
km2 <- survfit(Surv(prostate$time, prostate$status) ~ prostate$treatment) # el 1 es xq es sin grupos

plot(km2, mark.time = T)

```
```{r, log-rank test}
km2 %>% autoplot() #from ggfortify
survdiff(Surv(prostate$time, prostate$status) ~ prostate$treatment)

```

```{r, exercise}
data(motorette, package = "SMPracticals")

moto <- motorette
head(moto)

# x= temp in F
# cens= censoring indicator
# y= failure time in hours

plot(moto$x, moto$y)

Surv(moto$y, moto$cens)
survfit(Surv(moto$y, moto$cens) ~ 1)
moto_km1 <- survfit(Surv(moto$y, moto$cens) ~ 1)

moto_km1 %>% plot(mark.time = T)


moto <- moto %>% 
  mutate(temp_level = if_else(x < 180, "Low", "High"))

head(moto)

(moto_km2 <- survfit(Surv(moto$y, moto$cens) ~ moto$temp_level))

plot(moto_km2, mark.time = T)


survdiff(Surv(moto$y, moto$cens) ~ moto$temp_level)
```

```{r, coxph ex2}
df <- tibble(udca1)
dim(df)
head(df)

Surv(df$futime, df$status)

km_model <- survfit(Surv(futime, status) ~ trt, data = df)
autoplot(km_model)


cox_model <- coxph(Surv(futime, status) ~ trt + stage + bili + riskscore, data = df)
summary(cox_model)

cox_model2 <- coxph(Surv(futime, status) ~ trt + riskscore, data = df)
summary(cox_model2)
```

```{r, cox plot}
survfit(cox_model2) %>% autoplot()
```


```{r, lung dataset}
lung %>%  slice(3:5)

surv_obj <- Surv(lung$time, lung$status)

survfit(surv_obj ~ 1)

(surv_fit <- survfit(surv_obj ~ sex, data = lung))

survdiff(surv_obj ~ lung$sex)

survfit(surv_obj ~ lung$sex) %>% autoplot()


# survminer

ggsurvplot(surv_fit, 
           pval = T,
           conf.int = T,
           risk.table = T,
           surv.median.line = "hv",
           risk.table.col = "strata",
           ncensor.plot = T)


ggsurvplot(surv_fit, 
           pval = T,
           conf.int = T,
           risk.table = T,
           surv.median.line = "hv",
           risk.table.col = "strata",
           fun = "cumhaz")

ggsurvplot(surv_fit, 
           pval = T,
           conf.int = T,
           risk.table = T,
           surv.median.line = "hv",
           risk.table.col = "strata",
           fun = "event")

```






















